### ISSUE TITLE
Add Google Public DNS (8.8.8.8) to DNS Configuration -> Community Requested

### ISSUE THREAD

**Issue by DestroyerXyz** [safing/docs#43]
**What would you like to add or change?**:
Google Public DNS (8.8.8.8)
IPv4:
dot://8.8.8.8:853?verify=dns.google&name=Google&blockedif=zeroip
dot://8.8.4.4:853?verify=dns.google&name=Google&blockedif=zeroip
IPv6:
dot://[2001:4860:4860::8888]?verify=dns.google&name=Google&blockedif=zeroip
dot://[2001:4860:4860::8844]?verify=dns.google&name=Google&blockedif=zeroip

**Why do you and others need this?**:
It is the most popular public DNS, has very good coverage worldwide, and has very low latency.

**Comment by davegson** [comment]
Thanks for this suggestion, though I am honestly a bit torn about it. 

It does seem like a paradox for us who advocate for privacy so strongly to list Google DNS. Google definitely has great coverage, a fast service and airtight security. But the company does not care about user privacy. So many "free" Google services are just here to collect more and more user data to create better profiles which whey can then rent to advertisers.

On the other hand we clearly list "Community Suggestions", so it is not necessarily our word at stake.

Could you maybe extend what users get compared to just selecting the already listed Cloudflare, which also is a "mainstream" service with great coverage and low latency. 

Even if Cloudflare is also not known for privacy, from my point of view it is a better choice since it is harder for users to put all eggs in one basket, with many already using Google Chrome/Google Android/etc.

I might be over-conscious but want to get more input, both from you and from others in the team/community.

**Comment by DestroyerXyz** [comment]
Thanks for the quick reply

Where I live and probably throughout India, Google usually has much lower latency than Cloudflare, sometimes even 5 times as much. For example, I just did a test and Google was 15 ms while Cloudflare was 60 ms

Although I can't see any other reason besides that, I think that is a good enough reason for it to be mentioned in "Community Suggestions".

**Comment by davegson** [comment]
after talking with the team we will probably add a third category of "Community Requested" - softening the "suggestion" part of it a bit more. Thanks for the input and providing the settings for me to copy paste!

**Comment by DestroyerXyz** [comment]
I'm 14 by the way😁

**Comment by davegson** [comment]
cool! 💪 at that time I had no idea about firewalls or even what DNS was 😁

By the way, I would suggest not to share personal information online, especially not on public platforms where everybody can view the shared information. Nothing happened here and I deleted the comment so future viewers cannot see it, but as a lesson it is better to be too careful online than too open.

As to Google DNS, I just [opened a Pull Request](https://github.com/safing/docs/pull/44) and am waiting for my collegues to give their input. Should come out pretty soon ;)

**Comment by DestroyerXyz** [comment]
I was just coming back to delete it and saw your comment

**Comment by davegson** [comment]
just merged it, it is now live - thanks for the input
